# Generated by Django 4.2.5 on 2023-09-09 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0006_remove_shoppingcart_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='price',
        ),
    ]
