# Generated by Django 4.2.5 on 2023-09-09 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0009_remove_orderitem_price_remove_orderitem_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='price',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='unit_price',
        ),
    ]
