# Generated by Django 4.2.5 on 2023-09-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0010_remove_shoppingcart_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
